version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: athena-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: athena-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: athena-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data: